### ISSUE TITLE
Crash on v0.10.0 Debian Bullseye

### ISSUE THREAD

**Issue by Sadoon-AlBader** [Nheko-Reborn/nheko#1181]
I compiled v0.10.0 from source on Debian Bullseye and it seems to work fine on ppc64le (funnily) and crash on x86_64, tested multiple machines with the same issue.

```
[2022-09-06 13:09:34.229] [ui] [info] Restoring window size 1534x851
[2022-09-06 13:09:34.306] [ui] [info] jdenticon plugin not found.
[2022-09-06 13:09:34.502] [ui] [info] starting nheko 0.10.0-7df260f5
[2022-09-06 13:09:34.503] [ui] [info] User already signed in, showing chat page
[2022-09-06 13:09:34.503] [ui] [info] Switching to chat page
[2022-09-06 13:09:34.567] [ui] [info] Unity service available: false
[2022-09-06 13:09:34.572] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[2022-09-06 13:09:34.572] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
```

#1132 might be related

**Comment by nico-famedly** [comment]
Is that fixed in 0.10.1?

**Comment by deepbluev7** [comment]
Is that fixed in 0.10.1?

**Comment by squid-f** [comment]
Hi. I had crashes while signing in to the Matrix account, during the first start. 
After recompiling all the modules required to build (coeurl, mtxclient,…) and adding nheko-zsh-completion as recommended package (like openSUSE), there is no more crash.

**Comment by Sadoon-AlBader** [comment]
> Is that fixed in 0.10.1?

Doesn't seem to be for me.



> Hi. On Mageia 8, I had crashes while signing in to the Matrix account, during the first start. After recompiling all the modules required to build (coeurl, mtxclient,…) and adding nheko-zsh-completion as recommended package (like openSUSE), there is no more crash. The package is now released (community package) and used by some people.

Thanks I'll try that.

**Comment by Sadoon-AlBader** [comment]
It still doesn't work, I think this info might be helpful to the devs:

```
[2022-09-08 13:28:23.406] [ui] [info] Restoring window size 1214x998
[2022-09-08 13:28:23.435] [ui] [info] jdenticon plugin not found.
[2022-09-08 13:28:23.629] [ui] [debug] CompletionProxyModel: build trie: 19.291349 ms
[2022-09-08 13:28:23.670] [ui] [info] starting nheko 0.10.1-143d7c9b
[2022-09-08 13:28:23.671] [ui] [info] User already signed in, showing chat page
[2022-09-08 13:28:23.671] [db] [debug] setting up cache
[2022-09-08 13:28:23.671] [db] [debug] Reading 'm.cross_signing.master'
[2022-09-08 13:28:23.671] [ui] [info] Switching to chat page
[2022-09-08 13:28:23.697] [ui] [debug] Profile requested
[2022-09-08 13:28:23.719] [ui] [critical] Returning 0 spaces
[2022-09-08 13:28:23.735] [ui] [info] Unity service available: false
[2022-09-08 13:28:23.739] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[2022-09-08 13:28:23.739] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[2022-09-08 13:28:23.782] [qml] [debug] static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*) (:0, )
terminate called after throwing an instance of 'mtx::crypto::olm_exception'
  what():  identity_keys: account == nullptr
```


This happens if I press the settings button (nothing shows up in chats anyways)

I compiled with these options:

` cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_BUNDLED_OLM=Y -DUSE_BUNDLED_MTXCLIENT=Y -DUSE_BUNDLED_COEURL=Y -DVOIP=N -DUSE_BUNDLED_LMDBXX=Y`

**Comment by deepbluev7** [comment]
That sounds like your database/secure storage is corrupt. Maybe delete the database and settings file and login from scratch? (Or try a different profile)

**Comment by squid-f** [comment]
Might not be as important in this context, but just to say I don’t use any bundle for my build.

**Comment by Sadoon-AlBader** [comment]
> That sounds like your database/secure storage is corrupt. Maybe delete the database and settings file and login from scratch? (Or try a different profile)

I assume that means "~/.cache/nheko" and "~/.config/nheko"?

I already tried deleting those multiple times before posting :(

**Comment by deepbluev7** [comment]
I think it is mostly the database, which is in ~/.local/share/nheko

**Comment by Sadoon-AlBader** [comment]
> I think it is mostly the database, which is in ~/.local/share/nheko

Unfortunately deleting that did not work either.

**Comment by deepbluev7** [comment]
I'm assuming 0.10.2 didn't help either?

**Comment by Sadoon-AlBader** [comment]
> I'm assuming 0.10.2 didn't help either?

Just tested 0.10.2-fixes and it works fine.
