### ISSUE TITLE
Videocalling doesn't work on flatpak nheko

### ISSUE THREAD

**Issue by SamuelNorbury** [Nheko-Reborn/nheko#1293]
Version 0.11.0 of flatpak on ubuntu (vanilla os) complains that a glstreamer plugin is not available.

![image](https://user-images.githubusercontent.com/2980566/212553032-eb6cd60f-347c-49d4-8b84-8f1132789ea4.png)

**Comment by deepbluev7** [comment]
Should be fixed in https://github.com/Nheko-Reborn/nheko/commit/bbb551f2224a214cbc8e56272a3311fa7256d94f

If we can fix that in the flathub version depends a bit on if KDE releases their 5.15-22.08 runtime or not. If they don't, we will need to spend quite some effort trying to build the older gstreamer version.

**Comment by cam-rod** [comment]
Seeing a similar issue on 0.11.3 when trying to start a video call. Running the flatpak on Fedora 37:

```
Missing GStreamer plguins: qmlglsink
```

Somewhat related, the camera options don't seem correct. While I'm not able to start a video call, I can still see the camera (Logitech C920) listed in the app settings. However, it is limited to 920x760 resolution and 15 fps, while it should be capable of up to 1920x1080 and 30 fps.

**Comment by deepbluev7** [comment]
It should work fine on our nightlies, but on the flathub version we still use an older KDE runtime, since the newer one is not stable yet and we can't build the gstreamer plugin there.

**Comment by yajo** [comment]
Should this have been fixed by https://github.com/flathub/io.github.NhekoReborn.Nheko/pull/12? Because I can't still make my videocalls work without breaking nheko... 🤔

**Comment by deepbluev7** [comment]
The remaining issue seems to have been the egl issue on wayland. Please try the nightly flatpak to see, if you can still reproduce this.
