### ISSUE TITLE
"request key" either doesn't work or is slow and doesn't give progress feedback

### ISSUE THREAD

**Issue by raingloom** [Nheko-Reborn/nheko#888]
### Describe the bug

In Element the messages almost instantly become available, in Nheko nothing visible happens.

### To Reproduce

1. log out or get logged out due to an upgrade (i definitely did not log out in this case, but i'm not sure what else can cause it)
2. log back in and try to access messages sent from the same device with the previous session (they should show the "request key" prompt)
3. hit "request key" on them

I also did a device verification with another Nheko session. Not sure which of these steps is absolutely necessary and given that each logout could make messages inaccessible, I'm not super motivated to try them again.

### What happened?

Nothing. On the plus side there is no error message either.

### Expected behavior

Messages from the session that was forced to log out should appear immediately, like they do in Element. Or at least there should be an indication of what's going on and whether the user should just keep bashing that button or wait or log out and back in, or what.

### Version

0.9.1-4fca3c377f (postmarketOS) and 0.9.0 (Guix)

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

SXMO-Sway on pmOS and Sway on Guix

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Maybe these? `[2022-01-10 19:58:40.797] [crypto] [info] Could not find inbound megolm session`

There is a lot of them, looks like they are all the same, just a few milliseconds apart.
```

**Comment by deepbluev7** [comment]
Have you tried if closing and reopening Nheko shows the messages? There is also a 10 minute timeout, before hitting the button a second time does anything, if you hit it once before for that message. Does your other Nheko show, that it received any key requests?

**Comment by raingloom** [comment]
On Mon, 10 Jan 2022 11:05:13 -0800
"DeepBlueV7.X" ***@***.***> wrote:

> Have you tried if closing and reopening Nheko shows the messages?
> There is also a 10 minute timeout, before hitting the button a second
> time does anything, if you hit it once before for that message. Does
> your other Nheko show, that it received any key requests?
> 

Yup, restarted it a few times, at least on Guix. But
compared to "instant", "after a restart" is too long.

**Comment by deepbluev7** [comment]
That's just a bug with how we track what events we need to rerender. We actually have the decryption key already, but we forget to tell the UI to render the message again. It's known and at some point will be fixed.

**Comment by raingloom** [comment]
On Mon, 10 Jan 2022 11:44:01 -0800
"DeepBlueV7.X" ***@***.***> wrote:

> That's just a bug with how we track what events we need to rerender.
> We actually have the decryption key already, but we forget to tell
> the UI to render the message again. It's known and at some point will
> be fixed.
> 

Thanks, that clears things up!

ps.: Is there a way to close this from email? I'm trying to minimize
Github usage due to their handling of the ICE issue among other
reasons. Email is the best compromise I have for now between completely
abandoning it and still contributing to projects that use it
exclusively.

**Comment by deepbluev7** [comment]
No, but I will close it, once I fixed the issues, where the UI doesn't update. If you don't like github, feel free to report the issues on Matrix btw :3

**Comment by coldfix** [comment]
I had a similar experience.

This happened after first setting up my matrix account and connecting nheko as a second (or third?) client. I verified nheko successfully using the first client. The result was that nheko could decrypt and show the messages of the corresponding party, i.e. the "other" person in a chat room, while the messages of the logged in account were still shown as encrypted with "Request Key" button.

Clicking the button (with the first client being logged in the whole time) did not lead to any perceivable change, and this behaviour persistent even after waiting long times, multiple times of restarting nheko, more clicking, and I believe even logging in and out nheko. I had the same experience on several machines where I installed nheko and got it fixed only after exporting the session keys on the initial client and importing in nheko.

I got similar log messages as mentioned by the OP, but there was also another message that might have been more relevant. I can't quite remember and I now I seem unable to reproduce this problem, even after logging out nheko and deleting all of `~/.config/nheko`, `~/.cache/nheko`, `~/.local/share/nheko`, not sure what's going on. I might try doing this again with a completely fresh account..

**Comment by FlanOfHarmony** [comment]
Hi!
I'm having a similar problem. I have a matrix account and all my chat are encrypted, when I log into nheko it asks me for my security pass phrase, I input it, nothing happens for a while and then in the terminal log I get a lot of these `Could not find inbound megolm session` and It still asks for my security passphrase. Same thing with the security key.
